#!/usr/bin/python3

# Disclaimer: this code sucks because I don't like Python

import xml.etree.ElementTree as ET

tree = ET.parse('dev/map.tmx')
root = tree.getroot()

layer = root[1][0].text.replace("\n", "")
data = layer.split(",")

f = open("./src/mapdata.ts", "w")

f.write("// Generated by mapconv.py\n")
f.write("export const MAP_WIDTH = " + root.attrib['width'] + ";\n")
f.write("export const MAP_HEIGHT = " + root.attrib['height'] + ";\n")
f.write("export const MAP_DATA = [")

for i in range(0, len(data)):
    f.write(str(data[i]))
    if i < len(data)-1:
        f.write(",")

f.write("];\n")

f.close()
