#!/usr/bin/python3

# Disclaimer: this code sucks because I don't like Python

import xml.etree.ElementTree as ET

from os import listdir
from os.path import isfile, join

levels = [f for f in listdir("levels") if isfile(join("levels", f))]
levels.sort()


f = open("./src/mapdata.ts", "w")

f.write("// Generated by mapconv.py\n")

j = int(0)
for l in levels:

    tree = ET.parse('levels/' + l)
    root = tree.getroot()

    layer = root[1][0].text.replace("\n", "")
    data = layer.split(",")

    if j == 0:
        f.write("export const MAP_WIDTH = " + root.attrib['width'] + ";\n")
        f.write("export const MAP_HEIGHT = " + root.attrib['height'] + ";\n")
        f.write("export const MAP_DATA = [")

    f.write("[")

    for i in range(0, len(data)):
        f.write(str(data[i]))
        if i < len(data)-1:
            f.write(",")

    f.write("]")

    if j < len(levels)-1:
        f.write(",")
    j += 1

f.write("];\n")

f.close()
